### ISSUE TITLE
Resizable text field is bad ux

### ISSUE THREAD

**Issue by jacobkdick** [prescience-labs/landing-page#5]
![image](https://user-images.githubusercontent.com/13636529/63898182-13cd5c80-c9b5-11e9-87ef-45ffc60c492e.png)

This resizable text field, while in the user's control, can make the page weird.

Add `resize: none` on the textarea's css (preferably not directly in the `style` attribute but in some css file.

Set the `rows` attribute directly on the element. `rows` should be reasonable, like 5 or 6.

**Comment by jacobkdick** [comment]
To clarify, the default size of the text field is good. This image was taken after I resized the textarea using my mouse.

**Comment by corrortiz** [comment]
Fix in #8
